### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by philipsquire** [philipsquire/json-package#1]
## Introduce tools to an old web-based game

@egillespie Can you take a look at this? It's [hosted here](https://philipsquire-js-package-json-i.surge.sh/) and meets the following criteria:

- [x] Start your project with [these old game files](https://gist.github.com/egillespie/61d72035cd8c2639f07db1dbe2010605)
- [x] Convert the game's CSS to Sass, using variables, functions, and nesting where appropriate
- [x] Write a `dev` script in `package.json` that auto-compiles Sass and refreshes the browser at the same time
- [x] Write a `build` script in `package.json` that lints HTML, Sass, and JavaScript files before compiling Sass files (you can use these linters: [htmlhint](https://www.npmjs.com/package/htmlhint) for HTML, [stylelint](https://github.com/stylelint/stylelint/blob/HEAD/docs/user-guide/get-started.md) and [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard#installation) for Sass, [standard](https://www.npmjs.com/package/standard) for JavaScript)
- [x] All linting problems are fixed (problems will be displayed in the terminal when you run `npm run build`)
- [x] Write a `deploy` script in `package.json` that builds the project and uploads it to Surge if there are no errors
- [x] Unnecessary files like `node_modules` and your compiled CSS do not exist in your repository
- [x] Unnecessary files like `package.json` and `package-lock.json` are not uploaded to Surge

The scss and js linters refuse to install on my machine, and I can't figure out why. Everything else has been done to my best ability.

**Comment by philipsquire** [comment]
Good news! I fixed it with a clean install of npm! Everything works perfectly now!

**Comment by egillespie** [comment]
Awesome, I'm glad you were able to get them working! 👏 

Your project looks a-maz-ing. I can tell you paid close attention to all the details of this project — there are a lot of them! — and tested everything it. Your solutions are looking and working well! 🤘 

I have one recommendation to tighten up your scripts a bit: can you remove `npx` from the beginning of the linters? The `npx` tool is used to run commands installed to your `node_modules` directory but it's not required when commands run from `package.json` scripts. 😉 

After the change, comment back and I'll take a quick look!

**Comment by philipsquire** [comment]
Fixed it!

**Comment by egillespie** [comment]
Nailed it. Nice work! 🔨  :shipit:
